# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rusilomer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=200, verbose_name='Текст')),
                ('event_date', models.DateField(verbose_name='Дата проведения')),
                ('publication_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rusilomer.Location', verbose_name='Место проведения')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
