# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusilomer', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
    ]
