# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusilomer', '0003_auto_20170920_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Текст'),
        ),
    ]
